### ISSUE TITLE
Value removed from channel too early?

### ISSUE THREAD

**Issue by irgeek** [jasonbronson/go-concurrency-ratelimiting#1]
https://github.com/jasonbronson/go-concurrency-ratelimiting/blob/9ab85cebc8a44a484453c99101644a63986783b8/main.go#L44-L60

I just watched your video and I was a little confused by it. When you read from the channel on L50 -- before the actual _work_ of inserting into the DB is done -- aren't you just skipping the DB insert concurrency limit? It seems to me like you're limiting how many goroutines can be _starting_ concurrently, not how many can be _running_ concurrently.

**Comment by jasonbronson** [comment]
In this example it will fork out go routines for the insert itself. So in theory this example could be used with anything it doesn't have to be db inserts. 

Here is a better example
https://play.golang.org/p/EcDFFyiP29H

**Comment by irgeek** [comment]
Your Go Playground example also reads from the `guard` channel _after_ performing the work so it will indeed limit the concurrency. The example I quoted above reads from `guard` _before_ performing the work, so it's won't actually limit the concurrency of the work, just the concurrency of starting up goroutines.

**Comment by jasonbronson** [comment]
Ah good catch I will adjust the code.
